import { getTierFromOverall } from "./playerTier";
import { LegacyPlayerTier, Player, PlayerTier } from "../types";
import {
  PlayerTypeBadge,
  PlayerTypeBadgeDefinition,
  playerTypeBadgeDefinitions,
} from "./playerTypeBadges";

export interface CardLabCardConfig {
  id: string;
  player: Player;
  rarity: PlayerTier | LegacyPlayerTier;
  badgeType: PlayerTypeBadge;
  badgeCount: number;
  selected?: boolean;
  upgraded?: boolean;
  compact?: boolean;
  draftedPlayerIds?: string[];
}

export interface CardLabFocusPlayerConfig {
  id: string;
  label: string;
  player: Player;
  draftedPlayerIds?: string[];
}

export interface CardLabLinePreviewCard {
  id: string;
  label: string;
  variantLabel: string;
  player: Player;
  badgeType: PlayerTypeBadge;
  badgeCount: number;
  draftedPlayerIds?: string[];
}

export interface CardLabLinePreviewSection {
  id: string;
  title: string;
  description: string;
  cards: CardLabLinePreviewCard[];
}

const badgePriority: PlayerTypeBadge[] = [
  "sniper",
  "board-man",
  "playmaker",
  "lockdown",
  "slasher",
];

const createMockPlayer = ({
  id,
  name,
  teamLabel,
  era = "Card Lab",
  primaryPosition,
  secondaryPositions,
  overall,
  offense,
  defense,
  playmaking,
  shooting,
  rebounding,
  athleticism,
  intangibles,
  ballDominance,
  interiorDefense,
  perimeterDefense,
  archetype,
  shortDescription,
}: Omit<Player, "era" | "hallOfFameTier" | "badges" | "durability"> & { era?: string }): Player => ({
  id,
  name,
  era,
  teamLabel,
  primaryPosition,
  secondaryPositions,
  overall,
  offense,
  defense,
  playmaking,
  shooting,
  rebounding,
  athleticism,
  intangibles,
  durability: 92,
  archetype,
  hallOfFameTier: getTierFromOverall(overall),
  shortDescription,
  badges: [archetype],
  ballDominance,
  interiorDefense,
  perimeterDefense,
});

export const getCardLabBadgeDefinitions = (
  primary: PlayerTypeBadge,
  count: number,
): PlayerTypeBadgeDefinition[] => {
  const orderedTypes = [primary, ...badgePriority.filter((badgeType) => badgeType !== primary)];
  return orderedTypes
    .slice(0, Math.max(0, Math.min(count, orderedTypes.length)))
    .map((badgeType) => playerTypeBadgeDefinitions[badgeType]);
};

export const cardLabFocusPlayers: CardLabFocusPlayerConfig[] = [
  {
    id: "michael-jordan",
    label: "Michael Jordan",
    player: createMockPlayer({
      id: "michael-jordan",
      name: "Michael Jordan",
      teamLabel: "Chicago Bulls",
      primaryPosition: "SG",
      secondaryPositions: ["SF"],
      overall: 99,
      offense: 99,
      defense: 96,
      playmaking: 89,
      shooting: 92,
      rebounding: 78,
      athleticism: 98,
      intangibles: 99,
      ballDominance: 97,
      interiorDefense: 72,
      perimeterDefense: 97,
      archetype: "Two-way icon",
      shortDescription: "Explosive three-level scorer and elite perimeter killer built for premium card presentation tests.",
    }),
    draftedPlayerIds: ["michael-jordan", "scottie-pippen", "dennis-rodman-bulls"],
  },
  {
    id: "larry-bird",
    label: "Larry Bird",
    player: createMockPlayer({
      id: "larry-bird",
      name: "Larry Bird",
      teamLabel: "Boston Celtics",
      primaryPosition: "SF",
      secondaryPositions: ["PF"],
      overall: 97,
      offense: 97,
      defense: 85,
      playmaking: 92,
      shooting: 95,
      rebounding: 84,
      athleticism: 71,
      intangibles: 99,
      ballDominance: 82,
      interiorDefense: 65,
      perimeterDefense: 82,
      archetype: "Playmaking sniper",
      shortDescription: "Half-court genius with elite shotmaking, manipulation, and cold-blooded late-game feel.",
    }),
    draftedPlayerIds: ["larry-bird", "kevin-mchale", "robert-parish"],
  },
  {
    id: "anthony-edwards-2025-26",
    label: "Anthony Edwards",
    player: createMockPlayer({
      id: "anthony-edwards-2025-26",
      name: "Anthony Edwards",
      teamLabel: "Minnesota Timberwolves",
      primaryPosition: "SG",
      secondaryPositions: ["SF"],
      overall: 96,
      offense: 96,
      defense: 83,
      playmaking: 81,
      shooting: 88,
      rebounding: 67,
      athleticism: 97,
      intangibles: 91,
      ballDominance: 91,
      interiorDefense: 54,
      perimeterDefense: 82,
      archetype: "Explosive alpha scorer",
      shortDescription: "Power athlete with playoff swagger, elite downhill pressure, and rising shotmaking range.",
    }),
    draftedPlayerIds: ["anthony-edwards-2025-26", "julius-randle-2025-26", "rudy-gobert-2025-26"],
  },
  {
    id: "lebron-james-heat",
    label: "LeBron James ('10 - '14)",
    player: createMockPlayer({
      id: "lebron-james-heat",
      name: "LeBron James ('10 - '14)",
      teamLabel: "Miami Heat",
      primaryPosition: "SF",
      secondaryPositions: ["PF", "PG"],
      overall: 97,
      offense: 97,
      defense: 95,
      playmaking: 92,
      shooting: 79,
      rebounding: 80,
      athleticism: 99,
      intangibles: 96,
      ballDominance: 92,
      interiorDefense: 77,
      perimeterDefense: 95,
      archetype: "Two-way apex forward",
      shortDescription: "The peak Miami version with unstoppable transition force and devastating two-way coverage.",
    }),
    draftedPlayerIds: ["lebron-james-heat", "dwyane-wade-10-14", "chris-bosh"],
  },
  {
    id: "tim-duncan",
    label: "Tim Duncan",
    player: createMockPlayer({
      id: "tim-duncan",
      name: "Tim Duncan",
      teamLabel: "San Antonio Spurs",
      primaryPosition: "PF",
      secondaryPositions: ["C"],
      overall: 97,
      offense: 91,
      defense: 97,
      playmaking: 73,
      shooting: 72,
      rebounding: 94,
      athleticism: 77,
      intangibles: 99,
      ballDominance: 66,
      interiorDefense: 97,
      perimeterDefense: 72,
      archetype: "Fundamental anchor",
      shortDescription: "Quietly dominant two-way stabilizer who makes every lineup feel more structured and winning.",
    }),
    draftedPlayerIds: ["tim-duncan", "tony-parker", "manu-ginobili"],
  },
  {
    id: "shaquille-o-neal-magic",
    label: "Shaquille O'Neal (Magic)",
    player: createMockPlayer({
      id: "shaquille-o-neal-magic",
      name: "Shaquille O'Neal (Magic)",
      teamLabel: "Orlando Magic",
      primaryPosition: "C",
      secondaryPositions: [],
      overall: 95,
      offense: 95,
      defense: 84,
      playmaking: 58,
      shooting: 32,
      rebounding: 91,
      athleticism: 97,
      intangibles: 88,
      ballDominance: 74,
      interiorDefense: 88,
      perimeterDefense: 54,
      archetype: "Open-floor super center",
      shortDescription: "The most explosive Shaq build, mixing runway speed with impossible interior force.",
    }),
    draftedPlayerIds: ["shaquille-o-neal-magic", "penny-hardaway"],
  },
  {
    id: "giannis-antetokounmpo-2025-26",
    label: "Giannis Antetokounmpo",
    player: createMockPlayer({
      id: "giannis-antetokounmpo-2025-26",
      name: "Giannis Antetokounmpo",
      teamLabel: "Milwaukee Bucks",
      primaryPosition: "PF",
      secondaryPositions: ["SF", "C"],
      overall: 98,
      offense: 97,
      defense: 96,
      playmaking: 86,
      shooting: 68,
      rebounding: 92,
      athleticism: 99,
      intangibles: 96,
      ballDominance: 90,
      interiorDefense: 95,
      perimeterDefense: 82,
      archetype: "Two-way force of nature",
      shortDescription: "Rim-warping superstar whose length, speed, and pressure change the geometry of every possession.",
    }),
    draftedPlayerIds: ["giannis-antetokounmpo-2025-26", "damian-lillard", "khris-middleton"],
  },
];

export const cardLabMockCards: CardLabCardConfig[] = [
  {
    id: "lab-ace",
    player: cardLabFocusPlayers[0].player,
    rarity: "S",
    badgeType: "slasher",
    badgeCount: 4,
    upgraded: true,
    draftedPlayerIds: cardLabFocusPlayers[0].draftedPlayerIds,
  },
  {
    id: "lab-mason",
    player: createMockPlayer({
      id: "card-lab-mason-rhodes",
      name: "Mason Rhodes",
      teamLabel: "Steel Guardians",
      primaryPosition: "SF",
      secondaryPositions: ["PF", "SG"],
      overall: 93,
      offense: 86,
      defense: 96,
      playmaking: 79,
      shooting: 81,
      rebounding: 85,
      athleticism: 91,
      intangibles: 95,
      ballDominance: 68,
      interiorDefense: 87,
      perimeterDefense: 97,
      archetype: "Wing stopper",
      shortDescription: "Physical point-of-attack eraser who brings playoff-level resistance every possession.",
    }),
    rarity: "A",
    badgeType: "lockdown",
    badgeCount: 3,
    selected: true,
  },
  {
    id: "lab-luca",
    player: createMockPlayer({
      id: "card-lab-luca-valentine",
      name: "Luca Valentine",
      teamLabel: "Royal Orbit",
      primaryPosition: "PG",
      secondaryPositions: ["SG", "SF"],
      overall: 90,
      offense: 92,
      defense: 76,
      playmaking: 95,
      shooting: 85,
      rebounding: 70,
      athleticism: 82,
      intangibles: 90,
      ballDominance: 94,
      interiorDefense: 58,
      perimeterDefense: 77,
      archetype: "Tempo maestro",
      shortDescription: "Big creator who strings help defenders apart and controls the pace of an entire game.",
    }),
    rarity: "B",
    badgeType: "playmaker",
    badgeCount: 3,
  },
  {
    id: "lab-darius",
    player: createMockPlayer({
      id: "card-lab-darius-crown",
      name: "Darius Crown",
      teamLabel: "Summit Eclipse",
      primaryPosition: "SG",
      secondaryPositions: ["SF"],
      overall: 87,
      offense: 90,
      defense: 73,
      playmaking: 74,
      shooting: 93,
      rebounding: 63,
      athleticism: 95,
      intangibles: 80,
      ballDominance: 83,
      interiorDefense: 48,
      perimeterDefense: 72,
      archetype: "Pressure scorer",
      shortDescription: "Rim-pressure guard with burst, hang time, and just enough jumper gravity to stay honest.",
    }),
    rarity: "B",
    badgeType: "slasher",
    badgeCount: 2,
  },
  {
    id: "lab-orion",
    player: createMockPlayer({
      id: "card-lab-orion-banks",
      name: "Orion Banks",
      teamLabel: "Harbor Towers",
      primaryPosition: "PF",
      secondaryPositions: ["C"],
      overall: 83,
      offense: 77,
      defense: 84,
      playmaking: 63,
      shooting: 68,
      rebounding: 95,
      athleticism: 79,
      intangibles: 86,
      ballDominance: 41,
      interiorDefense: 88,
      perimeterDefense: 66,
      archetype: "Glass monster",
      shortDescription: "Rugged interior finisher who wins extra possessions and turns every miss into a fight.",
    }),
    rarity: "C",
    badgeType: "board-man",
    badgeCount: 2,
  },
  {
    id: "lab-soren",
    player: createMockPlayer({
      id: "card-lab-soren-price",
      name: "Soren Price",
      teamLabel: "Midnight Voltage",
      primaryPosition: "SF",
      secondaryPositions: ["SG", "PF"],
      overall: 78,
      offense: 74,
      defense: 72,
      playmaking: 67,
      shooting: 82,
      rebounding: 69,
      athleticism: 76,
      intangibles: 79,
      ballDominance: 58,
      interiorDefense: 57,
      perimeterDefense: 73,
      archetype: "Spacing connector",
      shortDescription: "Reliable role wing whose shooting and decision-making help every lineup breathe.",
    }),
    rarity: "D",
    badgeType: "sniper",
    badgeCount: 1,
    compact: true,
  },
];

export const cardLabCompactPreviewPlayers = [
  createMockPlayer({
    id: "card-lab-maxwell-st-james",
    name: "Maxwell St. James",
    teamLabel: "Velvet District",
    primaryPosition: "SG",
    secondaryPositions: ["SF"],
    overall: 95,
    offense: 95,
    defense: 82,
    playmaking: 86,
    shooting: 97,
    rebounding: 71,
    athleticism: 88,
    intangibles: 90,
    ballDominance: 88,
    interiorDefense: 53,
    perimeterDefense: 81,
    archetype: "Elegant bucket-getter",
    shortDescription: "Long-name stress test with premium shotmaking and graceful off-ball movement.",
  }),
  createMockPlayer({
    id: "card-lab-julian-alexander-cross",
    name: "Julian Alexander Cross",
    teamLabel: "Metro Signal",
    primaryPosition: "PF",
    secondaryPositions: ["C"],
    overall: 89,
    offense: 83,
    defense: 87,
    playmaking: 72,
    shooting: 74,
    rebounding: 92,
    athleticism: 84,
    intangibles: 88,
    ballDominance: 39,
    interiorDefense: 90,
    perimeterDefense: 70,
    archetype: "Anchor forward",
    shortDescription: "Long-name rebound-and-defense test focused on compact readability.",
  }),
  createMockPlayer({
    id: "card-lab-elias-montgomery",
    name: "Elias Montgomery",
    teamLabel: "Pacific Bloom",
    primaryPosition: "PG",
    secondaryPositions: ["SG", "SF"],
    overall: 92,
    offense: 91,
    defense: 78,
    playmaking: 97,
    shooting: 84,
    rebounding: 66,
    athleticism: 83,
    intangibles: 91,
    ballDominance: 95,
    interiorDefense: 46,
    perimeterDefense: 77,
    archetype: "Oversized table-setter",
    shortDescription: "Compact preview for a creator with multiple name lines and a crowded position label.",
  }),
];

const createBeforeTheGloryCard = ({
  id,
  label,
  variantLabel,
  name,
  teamLabel,
  era,
  primaryPosition,
  secondaryPositions,
  overall,
  offense,
  defense,
  playmaking,
  shooting,
  rebounding,
  athleticism,
  intangibles,
  ballDominance,
  interiorDefense,
  perimeterDefense,
  archetype,
  shortDescription,
  badgeType,
  badgeCount,
}: {
  id: string;
  label: string;
  variantLabel: string;
  name: string;
  teamLabel: string;
  era: string;
  primaryPosition: Player["primaryPosition"];
  secondaryPositions: Player["secondaryPositions"];
  overall: number;
  offense: number;
  defense: number;
  playmaking: number;
  shooting: number;
  rebounding: number;
  athleticism: number;
  intangibles: number;
  ballDominance: number;
  interiorDefense: number;
  perimeterDefense: number;
  archetype: string;
  shortDescription: string;
  badgeType: PlayerTypeBadge;
  badgeCount: number;
}): CardLabLinePreviewCard => ({
  id,
  label,
  variantLabel,
  badgeType,
  badgeCount,
  player: createMockPlayer({
    id,
    name,
    teamLabel,
    era,
    primaryPosition,
    secondaryPositions,
    overall,
    offense,
    defense,
    playmaking,
    shooting,
    rebounding,
    athleticism,
    intangibles,
    ballDominance,
    interiorDefense,
    perimeterDefense,
    archetype,
    shortDescription,
  }),
});

export const beforeTheGlorySections: CardLabLinePreviewSection[] = [
  {
    id: "guards",
    title: "Guards",
    description: "Young creators, shooters, and burst guards before their peak versions took over the league.",
    cards: [
      createBeforeTheGloryCard({
        id: "btg-stephen-curry",
        label: "Stephen Curry",
        variantLabel: "Rookie",
        name: "Stephen Curry",
        teamLabel: "Golden State Warriors",
        era: "Rookie",
        primaryPosition: "PG",
        secondaryPositions: ["SG"],
        overall: 84,
        offense: 82,
        defense: 56,
        playmaking: 78,
        shooting: 93,
        rebounding: 52,
        athleticism: 72,
        intangibles: 80,
        ballDominance: 74,
        interiorDefense: 38,
        perimeterDefense: 57,
        archetype: "Flash shooter",
        shortDescription: "Early Steph already bends the floor with elite shooting, but he is still slight and targetable on defense.",
        badgeType: "sniper",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-james-harden-thunder",
        label: "James Harden",
        variantLabel: "OKC Rookie",
        name: "James Harden",
        teamLabel: "Oklahoma City Thunder",
        era: "OKC Rookie",
        primaryPosition: "SG",
        secondaryPositions: ["PG"],
        overall: 80,
        offense: 84,
        defense: 61,
        playmaking: 76,
        shooting: 81,
        rebounding: 57,
        athleticism: 74,
        intangibles: 79,
        ballDominance: 73,
        interiorDefense: 42,
        perimeterDefense: 62,
        archetype: "Bench scorer",
        shortDescription: "The scoring craft is showing up, but this version is still a sixth-man shot creator rather than a full offense unto himself.",
        badgeType: "playmaker",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-russell-westbrook",
        label: "Russell Westbrook",
        variantLabel: "Rookie",
        name: "Russell Westbrook",
        teamLabel: "Oklahoma City Thunder",
        era: "Rookie",
        primaryPosition: "PG",
        secondaryPositions: ["SG"],
        overall: 84,
        offense: 78,
        defense: 68,
        playmaking: 75,
        shooting: 61,
        rebounding: 63,
        athleticism: 95,
        intangibles: 82,
        ballDominance: 78,
        interiorDefense: 52,
        perimeterDefense: 69,
        archetype: "Raw explosive guard",
        shortDescription: "The burst and attack mentality are already obvious, but the jumper and polish are still coming together.",
        badgeType: "slasher",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-damian-lillard",
        label: "Damian Lillard",
        variantLabel: "Rookie",
        name: "Damian Lillard",
        teamLabel: "Portland Trail Blazers",
        era: "Rookie",
        primaryPosition: "PG",
        secondaryPositions: ["SG"],
        overall: 83,
        offense: 85,
        defense: 60,
        playmaking: 82,
        shooting: 87,
        rebounding: 55,
        athleticism: 80,
        intangibles: 84,
        ballDominance: 82,
        interiorDefense: 41,
        perimeterDefense: 61,
        archetype: "Polished lead guard",
        shortDescription: "Already polished compared to most rookies, with a real pull-up package and instant lead-guard composure.",
        badgeType: "sniper",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-devin-booker",
        label: "Devin Booker",
        variantLabel: "Rookie",
        name: "Devin Booker",
        teamLabel: "Phoenix Suns",
        era: "Rookie",
        primaryPosition: "SG",
        secondaryPositions: ["PG"],
        overall: 81,
        offense: 80,
        defense: 57,
        playmaking: 70,
        shooting: 86,
        rebounding: 49,
        athleticism: 74,
        intangibles: 77,
        ballDominance: 67,
        interiorDefense: 36,
        perimeterDefense: 58,
        archetype: "Pure young shooter",
        shortDescription: "The jumper is real immediately, but he is not yet carrying primary scoring responsibility every night.",
        badgeType: "sniper",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "ja-morant",
        label: "Ja Morant",
        variantLabel: "Rookie",
        name: "Ja Morant",
        teamLabel: "Memphis Grizzlies",
        era: "Rookie",
        primaryPosition: "PG",
        secondaryPositions: ["SG"],
        overall: 83,
        offense: 84,
        defense: 58,
        playmaking: 84,
        shooting: 69,
        rebounding: 52,
        athleticism: 95,
        intangibles: 81,
        ballDominance: 84,
        interiorDefense: 40,
        perimeterDefense: 59,
        archetype: "Explosive downhill creator",
        shortDescription: "Ja is already warping the paint with burst and touch, but the all-around discipline is still developing.",
        badgeType: "slasher",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-kyrie-irving",
        label: "Kyrie Irving",
        variantLabel: "Rookie",
        name: "Kyrie Irving",
        teamLabel: "Cleveland Cavaliers",
        era: "Rookie",
        primaryPosition: "PG",
        secondaryPositions: ["SG"],
        overall: 82,
        offense: 84,
        defense: 55,
        playmaking: 82,
        shooting: 83,
        rebounding: 44,
        athleticism: 79,
        intangibles: 78,
        ballDominance: 83,
        interiorDefense: 32,
        perimeterDefense: 56,
        archetype: "Handle artist",
        shortDescription: "The handle and scoring creativity are already elite-feeling, but the early team impact is still limited.",
        badgeType: "playmaker",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-shai-gilgeous-alexander",
        label: "Shai Gilgeous-Alexander",
        variantLabel: "Rookie",
        name: "Shai Gilgeous-Alexander",
        teamLabel: "Los Angeles Clippers",
        era: "Rookie",
        primaryPosition: "PG",
        secondaryPositions: ["SG", "SF"],
        overall: 80,
        offense: 79,
        defense: 67,
        playmaking: 77,
        shooting: 74,
        rebounding: 56,
        athleticism: 80,
        intangibles: 79,
        ballDominance: 76,
        interiorDefense: 44,
        perimeterDefense: 68,
        archetype: "Smooth developing guard",
        shortDescription: "The pace and length are intriguing right away, but the full scoring takeover version has not arrived yet.",
        badgeType: "playmaker",
        badgeCount: 2,
      }),
    ],
  },
  {
    id: "wings",
    title: "Wings",
    description: "Raw two-way tools, early scorer flashes, and defense-first wings before superstardom fully hit.",
    cards: [
      createBeforeTheGloryCard({
        id: "btg-lebron-james-03-10",
        label: "LeBron James",
        variantLabel: "Rookie",
        name: "LeBron James",
        teamLabel: "Cleveland Cavaliers",
        era: "Rookie",
        primaryPosition: "SF",
        secondaryPositions: ["SG", "PG"],
        overall: 84,
        offense: 83,
        defense: 66,
        playmaking: 80,
        shooting: 66,
        rebounding: 71,
        athleticism: 98,
        intangibles: 86,
        ballDominance: 82,
        interiorDefense: 52,
        perimeterDefense: 67,
        archetype: "Generational raw wing",
        shortDescription: "The physical force is already overwhelming, but the jumper and half-court polish are still in progress.",
        badgeType: "slasher",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-kobe-bryant",
        label: "Kobe Bryant",
        variantLabel: "Rookie",
        name: "Kobe Bryant",
        teamLabel: "Los Angeles Lakers",
        era: "Rookie",
        primaryPosition: "SG",
        secondaryPositions: ["SF"],
        overall: 79,
        offense: 76,
        defense: 69,
        playmaking: 67,
        shooting: 73,
        rebounding: 60,
        athleticism: 88,
        intangibles: 79,
        ballDominance: 70,
        interiorDefense: 46,
        perimeterDefense: 70,
        archetype: "Explosive raw shot creator",
        shortDescription: "The burst, confidence, and difficult-shot appetite already stand out, even before the full superstar polish arrives.",
        badgeType: "slasher",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-kevin-durant-thunder",
        label: "Kevin Durant",
        variantLabel: "Rookie",
        name: "Kevin Durant",
        teamLabel: "Oklahoma City Thunder",
        era: "Rookie",
        primaryPosition: "SF",
        secondaryPositions: ["SG", "PF"],
        overall: 85,
        offense: 86,
        defense: 58,
        playmaking: 71,
        shooting: 85,
        rebounding: 68,
        athleticism: 79,
        intangibles: 80,
        ballDominance: 79,
        interiorDefense: 42,
        perimeterDefense: 59,
        archetype: "Lanky shotmaker",
        shortDescription: "The scoring ceiling is obvious instantly, but the frame and defensive resistance are still immature.",
        badgeType: "sniper",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-kawhi-leonard",
        label: "Kawhi Leonard",
        variantLabel: "Rookie",
        name: "Kawhi Leonard",
        teamLabel: "San Antonio Spurs",
        era: "Rookie",
        primaryPosition: "SF",
        secondaryPositions: ["SG", "PF"],
        overall: 78,
        offense: 68,
        defense: 87,
        playmaking: 62,
        shooting: 66,
        rebounding: 78,
        athleticism: 76,
        intangibles: 82,
        ballDominance: 55,
        interiorDefense: 61,
        perimeterDefense: 88,
        archetype: "Defense-first claw",
        shortDescription: "Rebounding and elite defensive instincts carry this version while the offensive toolkit still builds slowly.",
        badgeType: "lockdown",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-paul-george",
        label: "Paul George",
        variantLabel: "Rookie",
        name: "Paul George",
        teamLabel: "Indiana Pacers",
        era: "Rookie",
        primaryPosition: "SF",
        secondaryPositions: ["SG"],
        overall: 79,
        offense: 73,
        defense: 78,
        playmaking: 64,
        shooting: 74,
        rebounding: 63,
        athleticism: 80,
        intangibles: 78,
        ballDominance: 60,
        interiorDefense: 46,
        perimeterDefense: 79,
        archetype: "Raw two-way wing",
        shortDescription: "The length and two-way outline are there early, but the on-ball confidence has not fully arrived.",
        badgeType: "lockdown",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-jayson-tatum",
        label: "Jayson Tatum",
        variantLabel: "Rookie",
        name: "Jayson Tatum",
        teamLabel: "Boston Celtics",
        era: "Rookie",
        primaryPosition: "SF",
        secondaryPositions: ["PF", "SG"],
        overall: 82,
        offense: 84,
        defense: 72,
        playmaking: 68,
        shooting: 83,
        rebounding: 67,
        athleticism: 80,
        intangibles: 81,
        ballDominance: 74,
        interiorDefense: 48,
        perimeterDefense: 73,
        archetype: "Polished young scorer",
        shortDescription: "Already polished as a scorer compared to most young wings, with smoother footwork and cleaner shot creation.",
        badgeType: "sniper",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-jimmy-butler-bulls",
        label: "Jimmy Butler",
        variantLabel: "Early Bulls",
        name: "Jimmy Butler",
        teamLabel: "Chicago Bulls",
        era: "Early Bulls",
        primaryPosition: "SG",
        secondaryPositions: ["SF"],
        overall: 76,
        offense: 66,
        defense: 84,
        playmaking: 58,
        shooting: 67,
        rebounding: 63,
        athleticism: 77,
        intangibles: 80,
        ballDominance: 52,
        interiorDefense: 50,
        perimeterDefense: 85,
        archetype: "Low-usage stopper",
        shortDescription: "A defense-first grinder who already competes on every possession, before the heavy on-ball scoring load ever shows up.",
        badgeType: "lockdown",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-tracy-mcgrady-raptors",
        label: "Tracy McGrady",
        variantLabel: "Rookie",
        name: "Tracy McGrady",
        teamLabel: "Toronto Raptors",
        era: "Rookie",
        primaryPosition: "SF",
        secondaryPositions: ["SG"],
        overall: 79,
        offense: 72,
        defense: 65,
        playmaking: 61,
        shooting: 68,
        rebounding: 66,
        athleticism: 88,
        intangibles: 76,
        ballDominance: 58,
        interiorDefense: 44,
        perimeterDefense: 66,
        archetype: "Raw athlete wing",
        shortDescription: "The smooth athletic upside is obvious, but this is still a developmental version rather than the finished star.",
        badgeType: "slasher",
        badgeCount: 2,
      }),
    ],
  },
  {
    id: "bigs",
    title: "Bigs",
    description: "High-upside frontcourt foundations with clear strengths but not yet the finished superstar package.",
    cards: [
      createBeforeTheGloryCard({
        id: "btg-giannis-antetokounmpo",
        label: "Giannis Antetokounmpo",
        variantLabel: "Rookie",
        name: "Giannis Antetokounmpo",
        teamLabel: "Milwaukee Bucks",
        era: "Rookie",
        primaryPosition: "SF",
        secondaryPositions: ["PF", "C"],
        overall: 79,
        offense: 68,
        defense: 73,
        playmaking: 62,
        shooting: 52,
        rebounding: 70,
        athleticism: 89,
        intangibles: 78,
        ballDominance: 61,
        interiorDefense: 56,
        perimeterDefense: 70,
        archetype: "Skinny chaos athlete",
        shortDescription: "The frame is still thin and the skill set is raw, but the tools and open-floor menace are already fascinating.",
        badgeType: "slasher",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-nikola-jokic",
        label: "Nikola Jokic",
        variantLabel: "Rookie",
        name: "Nikola Jokic",
        teamLabel: "Denver Nuggets",
        era: "Rookie",
        primaryPosition: "C",
        secondaryPositions: ["PF"],
        overall: 82,
        offense: 78,
        defense: 62,
        playmaking: 83,
        shooting: 71,
        rebounding: 79,
        athleticism: 48,
        intangibles: 82,
        ballDominance: 67,
        interiorDefense: 68,
        perimeterDefense: 50,
        archetype: "Passing big teaser",
        shortDescription: "The passing flashes and touch are already unusual, even if the body and athletic profile still lag behind.",
        badgeType: "playmaker",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-joel-embiid",
        label: "Joel Embiid",
        variantLabel: "Early Career",
        name: "Joel Embiid",
        teamLabel: "Philadelphia 76ers",
        era: "Early Career",
        primaryPosition: "C",
        secondaryPositions: [],
        overall: 81,
        offense: 82,
        defense: 84,
        playmaking: 64,
        shooting: 72,
        rebounding: 82,
        athleticism: 73,
        intangibles: 76,
        ballDominance: 70,
        interiorDefense: 87,
        perimeterDefense: 58,
        archetype: "Dominant but limited big",
        shortDescription: "This version is already overpowering in short bursts, but conditioning and availability keep the profile from feeling complete.",
        badgeType: "board-man",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-anthony-davis",
        label: "Anthony Davis",
        variantLabel: "Rookie",
        name: "Anthony Davis",
        teamLabel: "New Orleans Pelicans",
        era: "Rookie",
        primaryPosition: "PF",
        secondaryPositions: ["C"],
        overall: 84,
        offense: 76,
        defense: 89,
        playmaking: 63,
        shooting: 66,
        rebounding: 84,
        athleticism: 84,
        intangibles: 80,
        ballDominance: 60,
        interiorDefense: 91,
        perimeterDefense: 68,
        archetype: "Young defensive terror",
        shortDescription: "Already a destructive defender and rim cleaner, while the offensive bag is still expanding.",
        badgeType: "lockdown",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "btg-dirk-nowitzki",
        label: "Dirk Nowitzki",
        variantLabel: "Rookie",
        name: "Dirk Nowitzki",
        teamLabel: "Dallas Mavericks",
        era: "Rookie",
        primaryPosition: "PF",
        secondaryPositions: ["C"],
        overall: 79,
        offense: 68,
        defense: 58,
        playmaking: 54,
        shooting: 72,
        rebounding: 67,
        athleticism: 63,
        intangibles: 73,
        ballDominance: 50,
        interiorDefense: 62,
        perimeterDefense: 45,
        archetype: "Stretch project",
        shortDescription: "The future superstar jumper is only a hint here, and the early adjustment period makes this version much shakier.",
        badgeType: "sniper",
        badgeCount: 1,
      }),
      createBeforeTheGloryCard({
        id: "btg-kevin-garnett-timberwolves",
        label: "Kevin Garnett",
        variantLabel: "Rookie",
        name: "Kevin Garnett",
        teamLabel: "Minnesota Timberwolves",
        era: "Rookie",
        primaryPosition: "PF",
        secondaryPositions: ["C", "SF"],
        overall: 80,
        offense: 74,
        defense: 83,
        playmaking: 67,
        shooting: 68,
        rebounding: 80,
        athleticism: 87,
        intangibles: 80,
        ballDominance: 63,
        interiorDefense: 83,
        perimeterDefense: 69,
        archetype: "Toolsy young unicorn",
        shortDescription: "The range of tools is obvious early, even if the offensive confidence and strength are still catching up.",
        badgeType: "lockdown",
        badgeCount: 2,
      }),
    ],
  },
  {
    id: "combo-stars",
    title: "Combo / Hybrid Stars",
    description: "Early all-around creators and scorers who were already useful, but not yet fully optimized peak engines.",
    cards: [
      createBeforeTheGloryCard({
        id: "dwyane-wade-03-10",
        label: "Dwyane Wade",
        variantLabel: "Rookie",
        name: "Dwyane Wade",
        teamLabel: "Miami Heat",
        era: "Rookie",
        primaryPosition: "SG",
        secondaryPositions: ["PG"],
        overall: 82,
        offense: 84,
        defense: 71,
        playmaking: 79,
        shooting: 66,
        rebounding: 58,
        athleticism: 90,
        intangibles: 82,
        ballDominance: 80,
        interiorDefense: 48,
        perimeterDefense: 72,
        archetype: "Immediate slashing impact",
        shortDescription: "Wade already changes games with downhill force and fearless scoring, even before he becomes a finished superstar.",
        badgeType: "slasher",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "chris-paul",
        label: "Chris Paul",
        variantLabel: "Rookie",
        name: "Chris Paul",
        teamLabel: "New Orleans Pelicans",
        era: "Rookie",
        primaryPosition: "PG",
        secondaryPositions: ["SG"],
        overall: 85,
        offense: 83,
        defense: 74,
        playmaking: 90,
        shooting: 78,
        rebounding: 48,
        athleticism: 78,
        intangibles: 86,
        ballDominance: 88,
        interiorDefense: 35,
        perimeterDefense: 75,
        archetype: "High-IQ table setter",
        shortDescription: "The game control and decision-making are already elite-level traits, making him impactful almost immediately.",
        badgeType: "playmaker",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "steve-nash",
        label: "Steve Nash",
        variantLabel: "Early Suns",
        name: "Steve Nash",
        teamLabel: "Phoenix Suns",
        era: "Early Suns",
        primaryPosition: "PG",
        secondaryPositions: ["SG"],
        overall: 75,
        offense: 77,
        defense: 53,
        playmaking: 84,
        shooting: 82,
        rebounding: 40,
        athleticism: 63,
        intangibles: 79,
        ballDominance: 79,
        interiorDefense: 24,
        perimeterDefense: 54,
        archetype: "Developing organizer",
        shortDescription: "The feel and passing are clear, but he is still far away from the MVP-level offensive conductor version.",
        badgeType: "playmaker",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "klay-thompson",
        label: "Klay Thompson",
        variantLabel: "Rookie",
        name: "Klay Thompson",
        teamLabel: "Golden State Warriors",
        era: "Rookie",
        primaryPosition: "SG",
        secondaryPositions: ["SF"],
        overall: 79,
        offense: 78,
        defense: 64,
        playmaking: 58,
        shooting: 86,
        rebounding: 53,
        athleticism: 72,
        intangibles: 77,
        ballDominance: 52,
        interiorDefense: 36,
        perimeterDefense: 65,
        archetype: "Young movement shooter",
        shortDescription: "The jumper is already high quality, but the full elite two-way off-ball monster version is still ahead.",
        badgeType: "sniper",
        badgeCount: 2,
      }),
      createBeforeTheGloryCard({
        id: "ray-allen-sonics",
        label: "Ray Allen",
        variantLabel: "Rookie",
        name: "Ray Allen",
        teamLabel: "Milwaukee Bucks",
        era: "Rookie",
        primaryPosition: "SG",
        secondaryPositions: ["SF"],
        overall: 81,
        offense: 83,
        defense: 62,
        playmaking: 69,
        shooting: 84,
        rebounding: 54,
        athleticism: 82,
        intangibles: 79,
        ballDominance: 70,
        interiorDefense: 38,
        perimeterDefense: 63,
        archetype: "Early scoring wing",
        shortDescription: "Already a clean scorer and athlete, though not yet the fully refined efficiency monster he later becomes.",
        badgeType: "sniper",
        badgeCount: 2,
      }),
    ],
  },
  {
    id: "depth",
    title: "Underrated Early Versions",
    description: "Useful depth pieces and future connectors whose later value was much bigger than their early overall suggested.",
    cards: [
      createBeforeTheGloryCard({
        id: "kyle-lowry",
        label: "Kyle Lowry",
        variantLabel: "Early Career",
        name: "Kyle Lowry",
        teamLabel: "Memphis Grizzlies",
        era: "Early Career",
        primaryPosition: "PG",
        secondaryPositions: ["SG"],
        overall: 76,
        offense: 72,
        defense: 70,
        playmaking: 73,
        shooting: 67,
        rebounding: 55,
        athleticism: 74,
        intangibles: 77,
        ballDominance: 68,
        interiorDefense: 36,
        perimeterDefense: 71,
        archetype: "Tough early guard",
        shortDescription: "Competitive and sturdy, but still a long way from the polished All-Star lead guard he becomes later.",
        badgeType: "playmaker",
        badgeCount: 1,
      }),
      createBeforeTheGloryCard({
        id: "draymond-green",
        label: "Draymond Green",
        variantLabel: "Rookie",
        name: "Draymond Green",
        teamLabel: "Golden State Warriors",
        era: "Rookie",
        primaryPosition: "PF",
        secondaryPositions: ["C", "SF"],
        overall: 74,
        offense: 60,
        defense: 79,
        playmaking: 68,
        shooting: 58,
        rebounding: 75,
        athleticism: 67,
        intangibles: 82,
        ballDominance: 54,
        interiorDefense: 77,
        perimeterDefense: 74,
        archetype: "Glue-guy disruptor",
        shortDescription: "Low raw stats, but the switching, feel, and connective value are already more useful than the box score suggests.",
        badgeType: "lockdown",
        badgeCount: 1,
      }),
      createBeforeTheGloryCard({
        id: "pascal-siakam",
        label: "Pascal Siakam",
        variantLabel: "Rookie",
        name: "Pascal Siakam",
        teamLabel: "Toronto Raptors",
        era: "Rookie",
        primaryPosition: "PF",
        secondaryPositions: ["C", "SF"],
        overall: 75,
        offense: 64,
        defense: 71,
        playmaking: 58,
        shooting: 54,
        rebounding: 73,
        athleticism: 82,
        intangibles: 76,
        ballDominance: 49,
        interiorDefense: 70,
        perimeterDefense: 63,
        archetype: "Energy big project",
        shortDescription: "An energy-forward version with motor and transition value, but still raw offensively before the scoring leap.",
        badgeType: "board-man",
        badgeCount: 1,
      }),
    ],
  },
];
