import { LegacyPlayerTier, Player, PlayerTier, StoredPlayerTier } from "../types";
import {
  PlayerTypeBadge,
  PlayerTypeBadgeDefinition,
  playerTypeBadgeDefinitions,
} from "./playerTypeBadges";

export interface CardLabCardConfig {
  id: string;
  player: Player;
  rarity: PlayerTier | LegacyPlayerTier;
  badgeType: PlayerTypeBadge;
  badgeCount: number;
  selected?: boolean;
  upgraded?: boolean;
  compact?: boolean;
  draftedPlayerIds?: string[];
}

export interface CardLabFocusPlayerConfig {
  id: string;
  label: string;
  player: Player;
  draftedPlayerIds?: string[];
}

const badgePriority: PlayerTypeBadge[] = [
  "sniper",
  "board-man",
  "playmaker",
  "lockdown",
  "slasher",
];

const createMockPlayer = ({
  id,
  name,
  teamLabel,
  primaryPosition,
  secondaryPositions,
  overall,
  offense,
  defense,
  playmaking,
  shooting,
  rebounding,
  athleticism,
  intangibles,
  ballDominance,
  interiorDefense,
  perimeterDefense,
  archetype,
  shortDescription,
}: Omit<Player, "era" | "hallOfFameTier" | "badges" | "durability">): Player => ({
  id,
  name,
  era: "Card Lab",
  teamLabel,
  primaryPosition,
  secondaryPositions,
  overall,
  offense,
  defense,
  playmaking,
  shooting,
  rebounding,
  athleticism,
  intangibles,
  durability: 92,
  archetype,
  hallOfFameTier: "Ruby" satisfies StoredPlayerTier,
  shortDescription,
  badges: [archetype],
  ballDominance,
  interiorDefense,
  perimeterDefense,
});

export const getCardLabBadgeDefinitions = (
  primary: PlayerTypeBadge,
  count: number,
): PlayerTypeBadgeDefinition[] => {
  const orderedTypes = [primary, ...badgePriority.filter((badgeType) => badgeType !== primary)];
  return orderedTypes
    .slice(0, Math.max(0, Math.min(count, orderedTypes.length)))
    .map((badgeType) => playerTypeBadgeDefinitions[badgeType]);
};

export const cardLabFocusPlayers: CardLabFocusPlayerConfig[] = [
  {
    id: "michael-jordan",
    label: "Michael Jordan",
    player: createMockPlayer({
      id: "michael-jordan",
      name: "Michael Jordan",
      teamLabel: "Chicago Bulls",
      primaryPosition: "SG",
      secondaryPositions: ["SF"],
      overall: 99,
      offense: 99,
      defense: 96,
      playmaking: 89,
      shooting: 92,
      rebounding: 78,
      athleticism: 98,
      intangibles: 99,
      ballDominance: 97,
      interiorDefense: 72,
      perimeterDefense: 97,
      archetype: "Two-way icon",
      shortDescription: "Explosive three-level scorer and elite perimeter killer built for premium card presentation tests.",
    }),
    draftedPlayerIds: ["michael-jordan", "scottie-pippen", "dennis-rodman-bulls"],
  },
  {
    id: "larry-bird",
    label: "Larry Bird",
    player: createMockPlayer({
      id: "larry-bird",
      name: "Larry Bird",
      teamLabel: "Boston Celtics",
      primaryPosition: "SF",
      secondaryPositions: ["PF"],
      overall: 97,
      offense: 97,
      defense: 85,
      playmaking: 92,
      shooting: 95,
      rebounding: 84,
      athleticism: 71,
      intangibles: 99,
      ballDominance: 82,
      interiorDefense: 65,
      perimeterDefense: 82,
      archetype: "Playmaking sniper",
      shortDescription: "Half-court genius with elite shotmaking, manipulation, and cold-blooded late-game feel.",
    }),
    draftedPlayerIds: ["larry-bird", "kevin-mchale", "robert-parish"],
  },
  {
    id: "anthony-edwards-2025-26",
    label: "Anthony Edwards",
    player: createMockPlayer({
      id: "anthony-edwards-2025-26",
      name: "Anthony Edwards",
      teamLabel: "Minnesota Timberwolves",
      primaryPosition: "SG",
      secondaryPositions: ["SF"],
      overall: 96,
      offense: 96,
      defense: 83,
      playmaking: 81,
      shooting: 88,
      rebounding: 67,
      athleticism: 97,
      intangibles: 91,
      ballDominance: 91,
      interiorDefense: 54,
      perimeterDefense: 82,
      archetype: "Explosive alpha scorer",
      shortDescription: "Power athlete with playoff swagger, elite downhill pressure, and rising shotmaking range.",
    }),
    draftedPlayerIds: ["anthony-edwards-2025-26", "julius-randle-2025-26", "rudy-gobert-2025-26"],
  },
  {
    id: "lebron-james-heat",
    label: "LeBron James ('10 - '14)",
    player: createMockPlayer({
      id: "lebron-james-heat",
      name: "LeBron James ('10 - '14)",
      teamLabel: "Miami Heat",
      primaryPosition: "SF",
      secondaryPositions: ["PF", "PG"],
      overall: 97,
      offense: 97,
      defense: 95,
      playmaking: 92,
      shooting: 79,
      rebounding: 80,
      athleticism: 99,
      intangibles: 96,
      ballDominance: 92,
      interiorDefense: 77,
      perimeterDefense: 95,
      archetype: "Two-way apex forward",
      shortDescription: "The peak Miami version with unstoppable transition force and devastating two-way coverage.",
    }),
    draftedPlayerIds: ["lebron-james-heat", "dwyane-wade-10-14", "chris-bosh"],
  },
  {
    id: "tim-duncan",
    label: "Tim Duncan",
    player: createMockPlayer({
      id: "tim-duncan",
      name: "Tim Duncan",
      teamLabel: "San Antonio Spurs",
      primaryPosition: "PF",
      secondaryPositions: ["C"],
      overall: 97,
      offense: 91,
      defense: 97,
      playmaking: 73,
      shooting: 72,
      rebounding: 94,
      athleticism: 77,
      intangibles: 99,
      ballDominance: 66,
      interiorDefense: 97,
      perimeterDefense: 72,
      archetype: "Fundamental anchor",
      shortDescription: "Quietly dominant two-way stabilizer who makes every lineup feel more structured and winning.",
    }),
    draftedPlayerIds: ["tim-duncan", "tony-parker", "manu-ginobili"],
  },
  {
    id: "shaquille-o-neal-magic",
    label: "Shaquille O'Neal (Magic)",
    player: createMockPlayer({
      id: "shaquille-o-neal-magic",
      name: "Shaquille O'Neal (Magic)",
      teamLabel: "Orlando Magic",
      primaryPosition: "C",
      secondaryPositions: [],
      overall: 95,
      offense: 95,
      defense: 84,
      playmaking: 58,
      shooting: 32,
      rebounding: 91,
      athleticism: 97,
      intangibles: 88,
      ballDominance: 74,
      interiorDefense: 88,
      perimeterDefense: 54,
      archetype: "Open-floor super center",
      shortDescription: "The most explosive Shaq build, mixing runway speed with impossible interior force.",
    }),
    draftedPlayerIds: ["shaquille-o-neal-magic", "penny-hardaway"],
  },
  {
    id: "giannis-antetokounmpo-2025-26",
    label: "Giannis Antetokounmpo",
    player: createMockPlayer({
      id: "giannis-antetokounmpo-2025-26",
      name: "Giannis Antetokounmpo",
      teamLabel: "Milwaukee Bucks",
      primaryPosition: "PF",
      secondaryPositions: ["SF", "C"],
      overall: 98,
      offense: 97,
      defense: 96,
      playmaking: 86,
      shooting: 68,
      rebounding: 92,
      athleticism: 99,
      intangibles: 96,
      ballDominance: 90,
      interiorDefense: 95,
      perimeterDefense: 82,
      archetype: "Two-way force of nature",
      shortDescription: "Rim-warping superstar whose length, speed, and pressure change the geometry of every possession.",
    }),
    draftedPlayerIds: ["giannis-antetokounmpo-2025-26", "damian-lillard", "khris-middleton"],
  },
];

export const cardLabMockCards: CardLabCardConfig[] = [
  {
    id: "lab-ace",
    player: cardLabFocusPlayers[0].player,
    rarity: "S",
    badgeType: "slasher",
    badgeCount: 4,
    upgraded: true,
    draftedPlayerIds: cardLabFocusPlayers[0].draftedPlayerIds,
  },
  {
    id: "lab-mason",
    player: createMockPlayer({
      id: "card-lab-mason-rhodes",
      name: "Mason Rhodes",
      teamLabel: "Steel Guardians",
      primaryPosition: "SF",
      secondaryPositions: ["PF", "SG"],
      overall: 93,
      offense: 86,
      defense: 96,
      playmaking: 79,
      shooting: 81,
      rebounding: 85,
      athleticism: 91,
      intangibles: 95,
      ballDominance: 68,
      interiorDefense: 87,
      perimeterDefense: 97,
      archetype: "Wing stopper",
      shortDescription: "Physical point-of-attack eraser who brings playoff-level resistance every possession.",
    }),
    rarity: "A",
    badgeType: "lockdown",
    badgeCount: 3,
    selected: true,
  },
  {
    id: "lab-luca",
    player: createMockPlayer({
      id: "card-lab-luca-valentine",
      name: "Luca Valentine",
      teamLabel: "Royal Orbit",
      primaryPosition: "PG",
      secondaryPositions: ["SG", "SF"],
      overall: 90,
      offense: 92,
      defense: 76,
      playmaking: 95,
      shooting: 85,
      rebounding: 70,
      athleticism: 82,
      intangibles: 90,
      ballDominance: 94,
      interiorDefense: 58,
      perimeterDefense: 77,
      archetype: "Tempo maestro",
      shortDescription: "Big creator who strings help defenders apart and controls the pace of an entire game.",
    }),
    rarity: "B",
    badgeType: "playmaker",
    badgeCount: 3,
  },
  {
    id: "lab-darius",
    player: createMockPlayer({
      id: "card-lab-darius-crown",
      name: "Darius Crown",
      teamLabel: "Summit Eclipse",
      primaryPosition: "SG",
      secondaryPositions: ["SF"],
      overall: 87,
      offense: 90,
      defense: 73,
      playmaking: 74,
      shooting: 93,
      rebounding: 63,
      athleticism: 95,
      intangibles: 80,
      ballDominance: 83,
      interiorDefense: 48,
      perimeterDefense: 72,
      archetype: "Pressure scorer",
      shortDescription: "Rim-pressure guard with burst, hang time, and just enough jumper gravity to stay honest.",
    }),
    rarity: "B",
    badgeType: "slasher",
    badgeCount: 2,
  },
  {
    id: "lab-orion",
    player: createMockPlayer({
      id: "card-lab-orion-banks",
      name: "Orion Banks",
      teamLabel: "Harbor Towers",
      primaryPosition: "PF",
      secondaryPositions: ["C"],
      overall: 83,
      offense: 77,
      defense: 84,
      playmaking: 63,
      shooting: 68,
      rebounding: 95,
      athleticism: 79,
      intangibles: 86,
      ballDominance: 41,
      interiorDefense: 88,
      perimeterDefense: 66,
      archetype: "Glass monster",
      shortDescription: "Rugged interior finisher who wins extra possessions and turns every miss into a fight.",
    }),
    rarity: "C",
    badgeType: "board-man",
    badgeCount: 2,
  },
  {
    id: "lab-soren",
    player: createMockPlayer({
      id: "card-lab-soren-price",
      name: "Soren Price",
      teamLabel: "Midnight Voltage",
      primaryPosition: "SF",
      secondaryPositions: ["SG", "PF"],
      overall: 78,
      offense: 74,
      defense: 72,
      playmaking: 67,
      shooting: 82,
      rebounding: 69,
      athleticism: 76,
      intangibles: 79,
      ballDominance: 58,
      interiorDefense: 57,
      perimeterDefense: 73,
      archetype: "Spacing connector",
      shortDescription: "Reliable role wing whose shooting and decision-making help every lineup breathe.",
    }),
    rarity: "D",
    badgeType: "sniper",
    badgeCount: 1,
    compact: true,
  },
];

export const cardLabCompactPreviewPlayers = [
  createMockPlayer({
    id: "card-lab-maxwell-st-james",
    name: "Maxwell St. James",
    teamLabel: "Velvet District",
    primaryPosition: "SG",
    secondaryPositions: ["SF"],
    overall: 95,
    offense: 95,
    defense: 82,
    playmaking: 86,
    shooting: 97,
    rebounding: 71,
    athleticism: 88,
    intangibles: 90,
    ballDominance: 88,
    interiorDefense: 53,
    perimeterDefense: 81,
    archetype: "Elegant bucket-getter",
    shortDescription: "Long-name stress test with premium shotmaking and graceful off-ball movement.",
  }),
  createMockPlayer({
    id: "card-lab-julian-alexander-cross",
    name: "Julian Alexander Cross",
    teamLabel: "Metro Signal",
    primaryPosition: "PF",
    secondaryPositions: ["C"],
    overall: 89,
    offense: 83,
    defense: 87,
    playmaking: 72,
    shooting: 74,
    rebounding: 92,
    athleticism: 84,
    intangibles: 88,
    ballDominance: 39,
    interiorDefense: 90,
    perimeterDefense: 70,
    archetype: "Anchor forward",
    shortDescription: "Long-name rebound-and-defense test focused on compact readability.",
  }),
  createMockPlayer({
    id: "card-lab-elias-montgomery",
    name: "Elias Montgomery",
    teamLabel: "Pacific Bloom",
    primaryPosition: "PG",
    secondaryPositions: ["SG", "SF"],
    overall: 92,
    offense: 91,
    defense: 78,
    playmaking: 97,
    shooting: 84,
    rebounding: 66,
    athleticism: 83,
    intangibles: 91,
    ballDominance: 95,
    interiorDefense: 46,
    perimeterDefense: 77,
    archetype: "Oversized table-setter",
    shortDescription: "Compact preview for a creator with multiple name lines and a crowded position label.",
  }),
];
